stages:
  - test

variables:
  PNPM_STORE: .pnpm-store

test:
  stage: test
  image: node:latest
  before_script:
    - cd $ROOT_DIR
    - npm install --global pnpm@latest-10
    - mkdir -p $PNPM_STORE
    - pnpm config set store-dir $PNPM_STORE
  script:
    - pnpm install
    - pnpm test
    - cp coverage/cobertura-coverage.xml ../frontend-coverage.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  cache:
    key:
      files:
        - $ROOT_DIR/pnpm-lock.yaml
    paths:
      - $ROOT_DIR/$PNPM_STORE
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: frontend-coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_MERGE_REQUEST_ID