stages:
  - trigger
  - coverage

.test-dir:
  trigger:
    include:
      - local: $ROOT_DIR/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - $ROOT_DIR/**/*

test-frontend:
  stage: trigger
  extends: .test-dir
  variables:
    ROOT_DIR: frontend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

test-backend:
  stage: trigger
  extends: .test-dir
  variables:
    ROOT_DIR: backend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

coverage-report:
  image: node:lts-alpine
  stage: coverage
  needs:
    - test-frontend
    - test-backend
  before_script:
    apk add --no-cache python3
    npm install -g cobertura-merge
  script:
    npx cobertura-merge -o coverage-full.xml backend=backend-coverage.xml frontend=frontend-coverage.xml
    python coverage-report.py
  coverage: '/coverage: (\d+\.\d+)%/'
  