stages:
  - check-formatting
  - lint
  - test

variables:
  BACK_DIR: $CI_PROJECT_DIR/backend
  FRONT_DIR: $CI_PROJECT_DIR/frontend

# ------------ Catch-all MR job that always passes ------------ #

dummy:
  stage: test
  image: alpine:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "placeholder, this is the only job that runs in MR flows that don't need a pipeline."

# ------------ Frontend Jobs ------------ #

.pnpm_cache: &pnpm_cache
  key:
    files:
      - $FRONT_DIR/pnpm-lock.yaml
  paths:
    - $FRONT_DIR/$PNPM_STORE

format-frontend:
  stage: check-formatting
  image: node:latest
  variables:
    PNPM_STORE: $FRONT_DIR/.pnpm-store
  before_script:
    - cd $FRONT_DIR
    - npm install --global pnpm@latest-10
    - mkdir -p $PNPM_STORE
    - pnpm config set store-dir $PNPM_STORE
  script:
    - pnpm install
    - pnpm format:check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - frontend/**/*

lint-frontend:
  stage: lint
  image: node:latest
  variables:
    PNPM_STORE: $FRONT_DIR/.pnpm-store
  before_script:
    - cd $FRONT_DIR
    - npm install --global pnpm@latest-10
    - mkdir -p $PNPM_STORE
    - pnpm config set store-dir $PNPM_STORE
  script:
    - pnpm install
    - pnpm lint --format=@gitlab-formatters/gitlab --output-file gl-codequality.json
  cache:
    - <<: *pnpm_cache
  artifacts:
    reports:
      codequality: $FRONT_DIR/gl-codequality.json
    expire_in: 2 days
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - frontend/**/*

test-frontend:
  stage: test
  image: node:latest
  variables:
    PNPM_STORE: $FRONT_DIR/.pnpm-store
    NODE_OPTIONS: "--no-webstorage"
  before_script:
    - cd $FRONT_DIR
    - npm install --global pnpm@latest-10
    - mkdir -p $PNPM_STORE
    - pnpm config set store-dir $PNPM_STORE
  script:
    - pnpm install
    - pnpm test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  cache:
    - <<: *pnpm_cache
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $FRONT_DIR/coverage/cobertura-coverage.xml
    expire_in: 2 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - frontend/**/*

# ------------ Backend Jobs ------------ #

.golang_cache: &golang_cache
  key:
    files:
      - $BACK_DIR/go.mod
      - $BACK_DIR/go.sum
  paths:
    - $BACK_DIR/.go/pkg/mod

.pacman_cache: &pacman_cache
  key:
    files:
      - $PACMAN_REQS
  paths:
    - $PACMAN_CACHE

format-backend:
  stage: check-formatting
  image: golang:latest
  variables:
    GOPATH: $BACK_DIR/.go
  cache:
    - <<: *golang_cache
  before_script:
    - cd $BACK_DIR
    - go mod tidy
  script:
    - make format
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - backend/**/*

lint-backend:
  stage: lint
  image: archlinux:latest
  variables:
    PACMAN_REQS: $BACK_DIR/.arch-requirements
    PACMAN_CACHE: $BACK_DIR/.pacman-cache
    GOPATH: $BACK_DIR/.go
  cache:
    - <<: *golang_cache
    - <<: *pacman_cache
  before_script:
    - cd $BACK_DIR
    - mkdir -p $PACMAN_CACHE
    - echo "CacheDir = $PACMAN_CACHE" >> /etc/pacman.conf
    - pacman -Syu --noconfirm
    - xargs -t -a $PACMAN_REQS pacman -S --noconfirm
    - export PATH="$GOPATH/bin:$PATH"
    - make tidy
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $GOPATH/bin v2.5.0
  script:
    - make lint
  artifacts:
    reports:
      codequality: $BACK_DIR/gl-codequality.json
    expire_in: 2 days
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - backend/**/*

test-backend:
  stage: test
  image: archlinux:latest
  variables:
    PACMAN_REQS: $BACK_DIR/.arch-requirements
    PACMAN_CACHE: $BACK_DIR/.pacman-cache
    GOPATH: $BACK_DIR/.go
  before_script:
    - cd $BACK_DIR
    - mkdir -p $PACMAN_CACHE
    - echo "CacheDir = $PACMAN_CACHE" >> /etc/pacman.conf
    - pacman -Syu --noconfirm
    - xargs -t -a $PACMAN_REQS pacman -S --noconfirm
    - export PATH="$GOPATH/bin:$PATH"
  script:
    - make test
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'
  cache:
    - <<: *golang_cache
    - <<: *pacman_cache
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $BACK_DIR/coverage/cobertura-coverage.xml
    expire_in: 2 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        compare_to: 'refs/heads/main'
        paths:
          - backend/**/*
