stages:
  - test

.test-dir:
  trigger:
    include:
      - local: $ROOT_DIR/.gitlab-ci.yml
    strategy: mirror
  rules:
    - changes:
      - $ROOT_DIR/**/*

test-frontend:
  stage: test
  extends: .test-dir
  variables:
    ROOT_DIR: ./frontend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

test-backend:
  stage: test
  extends: .test-dir
  variables:
    ROOT_DIR: ./backend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    