services:
  frontend:
    build:
      context: ./frontend
      args:
        - FREEZETAG_BACKEND_ADDRESS=backend
    image: freezetag/frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    image: freezetag/backend
    ports:
      - "3824:3824"
    volumes:
      - type: bind
        source: ./backend/data
        target: /backend/data
      - type: bind
        source: ./backend/plugins
        target: /backend/plugins

# volumes:
#   data:
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: ./backend/data
#   plugins:
#     driver: local
#     driver-opts:
#       type: none
#       o: bind
#       device: ./backend/plugins