stages:
  - test

variables:
  ALPINE_CACHE: $ROOT_DIR/.apk-cache
  ALPINE_REQS: $ROOT_DIR/.apk-requirements

.golang_cache: &golang_cache
  key:
    files:
      - $ROOT_DIR/go.mod
      - $ROOT_DIR/go.sum
  paths:
    - $ROOT_DIR/.go/pkg/mod

.alpine_cache: &alpine_cache
  key:
    files:
      - $ALPINE_REQS
  paths:
    - $ROOT_DIR/$ALPINE_CACHE

test:
  stage: test
  image: alpine:latest
  variables:
    APK_CACHE_DIR: $ALPINE_CACHE
  before_script:
    - mkdir -p $ALPINE_CACHE
    - apk update --cache-dir $ALPINE_CACHE
    - xargs -t -a $ALPINE_REQS apk add --cache-dir $ALPINE_CACHE
    - cd $ROOT_DIR
    - export GOPATH=$PWD/.go
    - export PATH="$GOPATH/bin:$PATH"
    - go mod tidy
    - go install github.com/boumenot/gocover-cobertura
  script:
    - chmod +x test.sh
    - ./test.sh
  coverage: '/coverage: \d+.\d+% of statements/'
  cache:
    - <<: *golang_cache
    - <<: *alpine_cache
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $ROOT_DIR/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - if: $CI_MERGE_REQUEST_ID