version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - copyloopvar
    - sqlclosecheck
  exclusions:
    paths:
      - .go/
      - .apk-cache/
      - mocks/
output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
      colors: true
    code-climate:
      path: ./gl-codequality.json
