// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/backend/` | (string & {});
};

export type AlbumsAlbumCreateRequest = {
    name: string;
    visibility_mode?: 0 | 1 | 2;
};

export type AlbumsAlbumImageRequest = {
    image_id: number;
};

export type AlbumsAlbumModifyRequest = {
    album_id: number;
    name?: string;
    visibility_mode?: 0 | 1;
};

export type AlbumsRenameAlbumRequest = {
    new_name: string;
};

export type AlbumsUserAlbumPermissionRequest = {
    album_id: number;
    permission?: 0 | 1 | 2;
    target_user_id: number;
};

export type ApiAlbumCreateResponse = {
    album_id?: number;
};

export type ApiBadRequestResponse = {
    error?: string;
};

export type ApiCancelledJobResponse = {
    uuid?: string;
};

export type ApiImageDeleteResponse = {
    file?: string;
    id?: number;
};

export type ApiLoginCredentials = {
    password: string;
    username: string;
};

export type ApiLoginFailResponse = {
    error?: string;
};

export type ApiLoginSuccessResponse = {
    token?: string;
};

export type ApiLoginUserResponse = {
    permissions?: Array<DataPermission>;
    user_id?: number;
};

export type ApiLogoutSuccessResponse = {
    status?: string;
};

export type ApiMessageResponse = {
    message?: string;
};

export type ApiMetadataResponse = {
    cameraMake?: string;
    cameraModel?: string;
    dateTaken?: number;
    dateUploaded?: number;
    fileName?: string;
    height?: number;
    latitude?: number;
    longitude?: number;
    width?: number;
};

export type ApiNotFoundResponse = {
    error?: string;
};

export type ApiPasswordChangeRequest = {
    current_password: string;
    new_password: string;
};

export type ApiPluginDisabledResponse = {
    disabled?: boolean;
};

export type ApiServerErrorResponse = {
    error?: string;
};

export type ApiTagAddResponse = {
    added?: Array<RepositoriesImageTagSuccess>;
    errors?: Array<RepositoriesImageTagFail>;
};

export type ApiTagCounts = {
    [key: string]: number;
};

export type ApiTagDeleteResponse = {
    deleted?: number;
};

export type ApiTagRemoveResponse = {
    deleted?: Array<RepositoriesImageTagSuccess>;
    errors?: Array<RepositoriesImageTagFail>;
};

export type DataPermission = {
    description?: string;
    name?: string;
    permission?: string;
};

export type DatabaseAlbum = {
    album_privacy?: DatabaseGlobalPrivacy;
    id?: number;
    name?: string;
    owner_id?: number;
    visibility_level?: DatabaseUserPrivacy;
};

export type DatabaseAlbumSharedUser = {
    permission?: DatabaseGlobalPrivacy;
    user_id?: number;
};

export type DatabaseGlobalPrivacy = 0 | 1;

export type DatabasePublicUser = {
    created_at?: number;
    id?: number;
    username?: string;
    visibility_mode?: number;
};

export type DatabaseUserPrivacy = 0 | 1 | 2;

export type JobsExampleResponse = {
    cancelled?: boolean;
    completed?: Array<RepositoriesImageUploadSuccess>;
    failed?: Array<{
        input?: ServicesFileJob;
        reason?: string;
    }>;
    in_progress?: Array<ServicesFileJob>;
    uuid?: string;
};

export type PluginsHookSignature = 0 | 1 | 2;

export type PluginsHookType = 0 | 1 | 2;

export type PluginsPluginHook = {
    friendly_name?: string;
    signature?: PluginsHookSignature;
    type?: PluginsHookType;
};

export type PluginsPluginInfo = {
    configurable?: boolean;
    enabled?: boolean;
    friendly_name?: string;
    hooks?: {
        [key: string]: PluginsPluginHook;
    };
    name?: string;
    version?: string;
};

export type PluginsPublicConfigField = {
    default?: unknown;
    description?: string;
    name?: string;
    protected?: boolean;
    value?: unknown;
};

export type RepositoriesImageTagFail = {
    id?: number;
    reason?: string;
};

export type RepositoriesImageTagSuccess = {
    count?: number;
    id?: number;
};

export type RepositoriesImageUploadSuccess = {
    filename?: string;
    id?: number;
};

export type ServicesApiCreateToken = {
    tokenId?: number;
    tokenString?: string;
};

export type ServicesFileJob = {
    name?: string;
};

export type ServicesJobSummary = {
    complete?: number;
    errors?: number;
    in_progress?: number;
    status?: string;
    title?: string;
    uuid?: string;
};

export type GetAlbumData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/album';
};

export type GetAlbumErrors = {
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetAlbumError = GetAlbumErrors[keyof GetAlbumErrors];

export type GetAlbumResponses = {
    /**
     * OK
     */
    200: Array<DatabaseAlbum>;
};

export type GetAlbumResponse = GetAlbumResponses[keyof GetAlbumResponses];

export type PostAlbumData = {
    /**
     * Create Album Payload
     */
    body: AlbumsAlbumCreateRequest;
    path?: never;
    query?: never;
    url: '/album';
};

export type PostAlbumErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostAlbumError = PostAlbumErrors[keyof PostAlbumErrors];

export type PostAlbumResponses = {
    /**
     * OK
     */
    200: ApiAlbumCreateResponse;
};

export type PostAlbumResponse = PostAlbumResponses[keyof PostAlbumResponses];

export type GetAlbumImageByIdData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/album/image/{id}';
};

export type GetAlbumImageByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetAlbumImageByIdError = GetAlbumImageByIdErrors[keyof GetAlbumImageByIdErrors];

export type GetAlbumImageByIdResponses = {
    /**
     * OK
     */
    200: Array<DatabaseAlbum>;
};

export type GetAlbumImageByIdResponse = GetAlbumImageByIdResponses[keyof GetAlbumImageByIdResponses];

export type DeleteAlbumByIdData = {
    body?: never;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}';
};

export type DeleteAlbumByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteAlbumByIdError = DeleteAlbumByIdErrors[keyof DeleteAlbumByIdErrors];

export type DeleteAlbumByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteAlbumByIdResponse = DeleteAlbumByIdResponses[keyof DeleteAlbumByIdResponses];

export type GetAlbumByIdData = {
    body?: never;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}';
};

export type GetAlbumByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetAlbumByIdError = GetAlbumByIdErrors[keyof GetAlbumByIdErrors];

export type GetAlbumByIdResponses = {
    /**
     * OK
     */
    200: DatabaseAlbum;
};

export type GetAlbumByIdResponse = GetAlbumByIdResponses[keyof GetAlbumByIdResponses];

export type GetAlbumByIdImagesData = {
    body?: never;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/images';
};

export type GetAlbumByIdImagesErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetAlbumByIdImagesError = GetAlbumByIdImagesErrors[keyof GetAlbumByIdImagesErrors];

export type GetAlbumByIdImagesResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type GetAlbumByIdImagesResponse = GetAlbumByIdImagesResponses[keyof GetAlbumByIdImagesResponses];

export type PostAlbumByIdImagesData = {
    /**
     * Add Image to Album Payload
     */
    body: AlbumsAlbumImageRequest;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/images';
};

export type PostAlbumByIdImagesErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostAlbumByIdImagesError = PostAlbumByIdImagesErrors[keyof PostAlbumByIdImagesErrors];

export type PostAlbumByIdImagesResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostAlbumByIdImagesResponse = PostAlbumByIdImagesResponses[keyof PostAlbumByIdImagesResponses];

export type DeleteAlbumByIdImagesByImageIdData = {
    /**
     * Remove Image from Album Payload
     */
    body: AlbumsAlbumImageRequest;
    path: {
        /**
         * Album ID
         */
        id: number;
        /**
         * Image ID
         */
        image_id: number;
    };
    query?: never;
    url: '/album/{id}/images/{image_id}';
};

export type DeleteAlbumByIdImagesByImageIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteAlbumByIdImagesByImageIdError = DeleteAlbumByIdImagesByImageIdErrors[keyof DeleteAlbumByIdImagesByImageIdErrors];

export type DeleteAlbumByIdImagesByImageIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteAlbumByIdImagesByImageIdResponse = DeleteAlbumByIdImagesByImageIdResponses[keyof DeleteAlbumByIdImagesByImageIdResponses];

export type PatchAlbumByIdNameData = {
    /**
     * Rename Album Payload
     */
    body: AlbumsRenameAlbumRequest;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/name';
};

export type PatchAlbumByIdNameErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PatchAlbumByIdNameError = PatchAlbumByIdNameErrors[keyof PatchAlbumByIdNameErrors];

export type PatchAlbumByIdNameResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PatchAlbumByIdNameResponse = PatchAlbumByIdNameResponses[keyof PatchAlbumByIdNameResponses];

export type GetAlbumByIdPermissionsData = {
    body?: never;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/permissions';
};

export type GetAlbumByIdPermissionsErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetAlbumByIdPermissionsError = GetAlbumByIdPermissionsErrors[keyof GetAlbumByIdPermissionsErrors];

export type GetAlbumByIdPermissionsResponses = {
    /**
     * OK
     */
    200: Array<DatabaseAlbumSharedUser>;
};

export type GetAlbumByIdPermissionsResponse = GetAlbumByIdPermissionsResponses[keyof GetAlbumByIdPermissionsResponses];

export type PutAlbumByIdPermissionsData = {
    /**
     * Set User Album Permission Payload
     */
    body: AlbumsUserAlbumPermissionRequest;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/permissions';
};

export type PutAlbumByIdPermissionsErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PutAlbumByIdPermissionsError = PutAlbumByIdPermissionsErrors[keyof PutAlbumByIdPermissionsErrors];

export type PutAlbumByIdPermissionsResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PutAlbumByIdPermissionsResponse = PutAlbumByIdPermissionsResponses[keyof PutAlbumByIdPermissionsResponses];

export type PatchAlbumByIdVisibilityData = {
    /**
     * Change Album Visibility Payload
     */
    body: AlbumsAlbumModifyRequest;
    path: {
        /**
         * Album ID
         */
        id: number;
    };
    query?: never;
    url: '/album/{id}/visibility';
};

export type PatchAlbumByIdVisibilityErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PatchAlbumByIdVisibilityError = PatchAlbumByIdVisibilityErrors[keyof PatchAlbumByIdVisibilityErrors];

export type PatchAlbumByIdVisibilityResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PatchAlbumByIdVisibilityResponse = PatchAlbumByIdVisibilityResponses[keyof PatchAlbumByIdVisibilityResponses];

export type DeleteFileDeleteByIdData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/file/delete/{id}';
};

export type DeleteFileDeleteByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type DeleteFileDeleteByIdError = DeleteFileDeleteByIdErrors[keyof DeleteFileDeleteByIdErrors];

export type DeleteFileDeleteByIdResponses = {
    /**
     * OK
     */
    200: ApiImageDeleteResponse;
};

export type DeleteFileDeleteByIdResponse = DeleteFileDeleteByIdResponses[keyof DeleteFileDeleteByIdResponses];

export type GetFileDownloadByIdData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/file/download/{id}';
};

export type GetFileDownloadByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetFileDownloadByIdError = GetFileDownloadByIdErrors[keyof GetFileDownloadByIdErrors];

export type GetFileDownloadByIdResponses = {
    /**
     * thumbnail file data
     */
    200: unknown;
};

export type PostJobsCancelByIdData = {
    body?: never;
    path: {
        /**
         * Job Batch UUID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/cancel/{id}';
};

export type PostJobsCancelByIdErrors = {
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
};

export type PostJobsCancelByIdError = PostJobsCancelByIdErrors[keyof PostJobsCancelByIdErrors];

export type PostJobsCancelByIdResponses = {
    /**
     * OK
     */
    200: ApiCancelledJobResponse;
};

export type PostJobsCancelByIdResponse = PostJobsCancelByIdResponses[keyof PostJobsCancelByIdResponses];

export type GetJobsDetailsByIdData = {
    body?: never;
    path: {
        /**
         * Job Batch UUID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/details/{id}';
};

export type GetJobsDetailsByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
};

export type GetJobsDetailsByIdError = GetJobsDetailsByIdErrors[keyof GetJobsDetailsByIdErrors];

export type GetJobsDetailsByIdResponses = {
    /**
     * OK
     */
    200: JobsExampleResponse;
};

export type GetJobsDetailsByIdResponse = GetJobsDetailsByIdResponses[keyof GetJobsDetailsByIdResponses];

export type GetJobsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/list';
};

export type GetJobsListResponses = {
    /**
     * OK
     */
    200: Array<ServicesJobSummary>;
};

export type GetJobsListResponse = GetJobsListResponses[keyof GetJobsListResponses];

export type GetJobsSummaryByIdData = {
    body?: never;
    path: {
        /**
         * Job Batch UUID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/summary/{id}';
};

export type GetJobsSummaryByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
};

export type GetJobsSummaryByIdError = GetJobsSummaryByIdErrors[keyof GetJobsSummaryByIdErrors];

export type GetJobsSummaryByIdResponses = {
    /**
     * OK
     */
    200: ServicesJobSummary;
};

export type GetJobsSummaryByIdResponse = GetJobsSummaryByIdResponses[keyof GetJobsSummaryByIdResponses];

export type GetLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login';
};

export type GetLoginErrors = {
    /**
     * User is not authenticated
     */
    401: ApiLoginFailResponse;
};

export type GetLoginError = GetLoginErrors[keyof GetLoginErrors];

export type GetLoginResponses = {
    /**
     * user is authenticated
     */
    200: ApiLoginUserResponse;
};

export type GetLoginResponse = GetLoginResponses[keyof GetLoginResponses];

export type PostLoginData = {
    /**
     * User Login Details
     */
    body: ApiLoginCredentials;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Unauthorized
     */
    401: ApiLoginFailResponse;
};

export type PostLoginError = PostLoginErrors[keyof PostLoginErrors];

export type PostLoginResponses = {
    /**
     * Authentication successful
     */
    200: ApiLoginSuccessResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ApiLoginFailResponse;
};

export type PostLogoutError = PostLogoutErrors[keyof PostLogoutErrors];

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: ApiLogoutSuccessResponse;
};

export type PostLogoutResponse = PostLogoutResponses[keyof PostLogoutResponses];

export type GetMetadataByIdData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/metadata/{id}';
};

export type GetMetadataByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetMetadataByIdError = GetMetadataByIdErrors[keyof GetMetadataByIdErrors];

export type GetMetadataByIdResponses = {
    /**
     * OK
     */
    200: ApiMetadataResponse;
};

export type GetMetadataByIdResponse = GetMetadataByIdResponses[keyof GetMetadataByIdResponses];

export type PostPasswordChangeData = {
    /**
     * Password Change Request
     */
    body: ApiPasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/password/change';
};

export type PostPasswordChangeErrors = {
    /**
     * Invalid request
     */
    400: ApiBadRequestResponse;
    /**
     * User not authenticated
     */
    401: ApiBadRequestResponse;
    /**
     * Failed to change password
     */
    500: ApiBadRequestResponse;
};

export type PostPasswordChangeError = PostPasswordChangeErrors[keyof PostPasswordChangeErrors];

export type PostPasswordChangeResponses = {
    /**
     * Password changed successfully
     */
    200: ApiMessageResponse;
};

export type PostPasswordChangeResponse = PostPasswordChangeResponses[keyof PostPasswordChangeResponses];

export type GetPermissionsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/permissions/list';
};

export type GetPermissionsListResponses = {
    /**
     * List of permission names
     */
    200: Array<DataPermission>;
};

export type GetPermissionsListResponse = GetPermissionsListResponses[keyof GetPermissionsListResponses];

export type GetPluginsConfigData = {
    body?: never;
    path?: never;
    query: {
        /**
         * plugin to read configuration from
         */
        plugin: string;
    };
    url: '/plugins/config';
};

export type GetPluginsConfigErrors = {
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetPluginsConfigError = GetPluginsConfigErrors[keyof GetPluginsConfigErrors];

export type GetPluginsConfigResponses = {
    /**
     * plugin configuration
     */
    200: {
        [key: string]: PluginsPublicConfigField;
    };
};

export type GetPluginsConfigResponse = GetPluginsConfigResponses[keyof GetPluginsConfigResponses];

export type PostPluginsConfigData = {
    /**
     * field updates
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query: {
        /**
         * plugin to change
         */
        plugin: string;
    };
    url: '/plugins/config';
};

export type PostPluginsConfigErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostPluginsConfigError = PostPluginsConfigErrors[keyof PostPluginsConfigErrors];

export type PostPluginsConfigResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostPluginsConfigResponse = PostPluginsConfigResponses[keyof PostPluginsConfigResponses];

export type PostPluginsEnableData = {
    body?: never;
    path?: never;
    query: {
        /**
         * plugin to enable/disable
         */
        plugin: string;
        /**
         * whether the plugin should be enabled
         */
        enabled: boolean;
    };
    url: '/plugins/enable';
};

export type PostPluginsEnableErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type PostPluginsEnableError = PostPluginsEnableErrors[keyof PostPluginsEnableErrors];

export type PostPluginsEnableResponses = {
    /**
     * OK
     */
    200: Array<ApiPluginDisabledResponse>;
};

export type PostPluginsEnableResponse = PostPluginsEnableResponses[keyof PostPluginsEnableResponses];

export type GetPluginsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plugins/list';
};

export type GetPluginsListResponses = {
    /**
     * OK
     */
    200: Array<PluginsPluginInfo>;
};

export type GetPluginsListResponse = GetPluginsListResponses[keyof GetPluginsListResponses];

export type PostPluginsRunData = {
    /**
     * input to hook
     */
    body: unknown;
    path?: never;
    query: {
        /**
         * plugin to run
         */
        plugin: string;
        /**
         * hook to run
         */
        hook: string;
    };
    url: '/plugins/run';
};

export type PostPluginsRunErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type PostPluginsRunError = PostPluginsRunErrors[keyof PostPluginsRunErrors];

export type PostPluginsRunResponses = {
    /**
     * the UUID of the created job for the plugin run
     */
    202: string;
};

export type PostPluginsRunResponse = PostPluginsRunResponses[keyof PostPluginsRunResponses];

export type PostPluginsUploadData = {
    /**
     * link to pull from
     */
    body: string;
    path?: never;
    query?: never;
    url: '/plugins/upload';
};

export type PostPluginsUploadErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Not Found
     */
    404: ApiNotFoundResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostPluginsUploadError = PostPluginsUploadErrors[keyof PostPluginsUploadErrors];

export type PostPluginsUploadResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostPluginsUploadResponse = PostPluginsUploadResponses[keyof PostPluginsUploadResponses];

export type GetSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * camera make
         */
        make?: string;
        /**
         * camera make fuzzy
         */
        makeLike?: string;
        /**
         * camera model
         */
        model?: string;
        /**
         * camera model fuzzy
         */
        modelLike?: string;
        /**
         * picture taken before (unix epoch)
         */
        takenBefore?: string;
        /**
         * picture taken after (unix epoch)
         */
        takenAfter?: string;
        /**
         * picture uploaded before (unix epoch)
         */
        uploadedBefore?: string;
        /**
         * picture uploaded after (unix epoch)
         */
        uploadedAfter?: string;
        /**
         * latitude/longitude/distance (degrees)
         */
        near?: string;
        /**
         * picture tag
         */
        tag?: Array<string>;
        /**
         * picture tag fuzzy
         */
        tagLike?: Array<string>;
        /**
         * sort by
         */
        sortBy?: 'DateAdded' | 'DateCreated';
        /**
         * sort order
         */
        sortOrder?: 'ASC' | 'DESC';
        /**
         * page size
         */
        pageSize?: number;
        /**
         * page number (zero indexed)
         */
        pageNo?: number;
    };
    url: '/search';
};

export type GetSearchErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetSearchError = GetSearchErrors[keyof GetSearchErrors];

export type GetSearchResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type GetSearchResponse = GetSearchResponses[keyof GetSearchResponses];

export type PostTagAddData = {
    body?: never;
    path?: never;
    query: {
        /**
         * tags to add
         */
        tag: Array<string>;
        /**
         * image IDs to add to (optional)
         */
        id?: Array<number>;
    };
    url: '/tag/add';
};

export type PostTagAddErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type PostTagAddError = PostTagAddErrors[keyof PostTagAddErrors];

export type PostTagAddResponses = {
    /**
     * OK
     */
    200: ApiTagAddResponse;
};

export type PostTagAddResponse = PostTagAddResponses[keyof PostTagAddResponses];

export type GetTagCountsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * image IDs to get tag counts for
         */
        id: Array<string>;
    };
    url: '/tag/counts';
};

export type GetTagCountsErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetTagCountsError = GetTagCountsErrors[keyof GetTagCountsErrors];

export type GetTagCountsResponses = {
    /**
     * OK
     */
    200: ApiTagCounts;
};

export type GetTagCountsResponse = GetTagCountsResponses[keyof GetTagCountsResponses];

export type DeleteTagDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * tags to delete
         */
        tag: Array<string>;
    };
    url: '/tag/delete';
};

export type DeleteTagDeleteErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type DeleteTagDeleteError = DeleteTagDeleteErrors[keyof DeleteTagDeleteErrors];

export type DeleteTagDeleteResponses = {
    /**
     * OK
     */
    200: ApiTagDeleteResponse;
};

export type DeleteTagDeleteResponse = DeleteTagDeleteResponses[keyof DeleteTagDeleteResponses];

export type GetTagListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tag/list';
};

export type GetTagListErrors = {
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetTagListError = GetTagListErrors[keyof GetTagListErrors];

export type GetTagListResponses = {
    /**
     * OK
     */
    200: ApiTagCounts;
};

export type GetTagListResponse = GetTagListResponses[keyof GetTagListResponses];

export type GetTagListByIdData = {
    body?: never;
    path: {
        /**
         * image ID to get the tags of
         */
        id: number;
    };
    query?: never;
    url: '/tag/list/{id}';
};

export type GetTagListByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetTagListByIdError = GetTagListByIdErrors[keyof GetTagListByIdErrors];

export type GetTagListByIdResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetTagListByIdResponse = GetTagListByIdResponses[keyof GetTagListByIdResponses];

export type DeleteTagRemoveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * tags to remove
         */
        tag: Array<string>;
        /**
         * image IDs to remove from
         */
        id: Array<number>;
    };
    url: '/tag/remove';
};

export type DeleteTagRemoveErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
};

export type DeleteTagRemoveError = DeleteTagRemoveErrors[keyof DeleteTagRemoveErrors];

export type DeleteTagRemoveResponses = {
    /**
     * OK
     */
    200: ApiTagRemoveResponse;
};

export type DeleteTagRemoveResponse = DeleteTagRemoveResponses[keyof DeleteTagRemoveResponses];

export type GetTagSearchData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * camera make
         */
        make?: string;
        /**
         * camera make fuzzy
         */
        makeLike?: string;
        /**
         * camera model
         */
        model?: string;
        /**
         * camera model fuzzy
         */
        modelLike?: string;
        /**
         * picture taken before (unix epoch)
         */
        takenBefore?: string;
        /**
         * picture taken after (unix epoch)
         */
        takenAfter?: string;
        /**
         * picture uploaded before (unix epoch)
         */
        uploadedBefore?: string;
        /**
         * picture uploaded after (unix epoch)
         */
        uploadedAfter?: string;
        /**
         * latitude/longitude/distance (degrees)
         */
        near?: string;
        /**
         * picture tag
         */
        tag?: Array<string>;
        /**
         * picture tag fuzzy
         */
        tagLike?: Array<string>;
        /**
         * sort by
         */
        sortBy?: 'DateAdded' | 'DateCreated';
        /**
         * sort order
         */
        sortOrder?: 'ASC' | 'DESC';
        /**
         * page size
         */
        pageSize?: number;
        /**
         * page number (zero indexed)
         */
        pageNo?: number;
    };
    url: '/tag/search';
};

export type GetTagSearchErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetTagSearchError = GetTagSearchErrors[keyof GetTagSearchErrors];

export type GetTagSearchResponses = {
    /**
     * OK
     */
    200: ApiTagCounts;
};

export type GetTagSearchResponse = GetTagSearchResponses[keyof GetTagSearchResponses];

export type GetThumbnailsByIdData = {
    body?: never;
    path: {
        /**
         * Image ID
         */
        id: number;
    };
    query?: never;
    url: '/thumbnails/{id}';
};

export type GetThumbnailsByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetThumbnailsByIdError = GetThumbnailsByIdErrors[keyof GetThumbnailsByIdErrors];

export type GetThumbnailsByIdResponses = {
    /**
     * thumbnail file data
     */
    200: unknown;
};

export type DeleteTokensAdminDeleteByIdData = {
    body?: never;
    path: {
        /**
         * ID of the token to delete
         */
        id: string;
    };
    query?: never;
    url: '/tokens/admin/delete/{id}';
};

export type DeleteTokensAdminDeleteByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteTokensAdminDeleteByIdError = DeleteTokensAdminDeleteByIdErrors[keyof DeleteTokensAdminDeleteByIdErrors];

export type DeleteTokensAdminDeleteByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteTokensAdminDeleteByIdResponse = DeleteTokensAdminDeleteByIdResponses[keyof DeleteTokensAdminDeleteByIdResponses];

export type PostTokensAdminRevokeByIdData = {
    body?: never;
    path: {
        /**
         * ID of the token to revoke
         */
        id: string;
    };
    query?: never;
    url: '/tokens/admin/revoke/{id}';
};

export type PostTokensAdminRevokeByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostTokensAdminRevokeByIdError = PostTokensAdminRevokeByIdErrors[keyof PostTokensAdminRevokeByIdErrors];

export type PostTokensAdminRevokeByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostTokensAdminRevokeByIdResponse = PostTokensAdminRevokeByIdResponses[keyof PostTokensAdminRevokeByIdResponses];

export type PostTokensCreateData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Optional label for the token
         */
        label?: string;
        /**
         * Optional expiration time for the token in RFC3339 format (e.g. 2024-01-01T00:00:00Z)
         */
        expiresAt?: string;
        /**
         * List of permissions to assign to the token
         */
        permission: Array<string>;
    };
    url: '/tokens/create';
};

export type PostTokensCreateErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Unauthorized
     */
    401: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostTokensCreateError = PostTokensCreateErrors[keyof PostTokensCreateErrors];

export type PostTokensCreateResponses = {
    /**
     * OK
     */
    200: ServicesApiCreateToken;
};

export type PostTokensCreateResponse = PostTokensCreateResponses[keyof PostTokensCreateResponses];

export type PostTokensRevokeByIdData = {
    body?: never;
    path: {
        /**
         * ID of the token to revoke
         */
        id: string;
    };
    query?: never;
    url: '/tokens/revoke/{id}';
};

export type PostTokensRevokeByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Unauthorized
     */
    401: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostTokensRevokeByIdError = PostTokensRevokeByIdErrors[keyof PostTokensRevokeByIdErrors];

export type PostTokensRevokeByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostTokensRevokeByIdResponse = PostTokensRevokeByIdResponses[keyof PostTokensRevokeByIdResponses];

export type PostUploadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/upload';
};

export type PostUploadErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostUploadError = PostUploadErrors[keyof PostUploadErrors];

export type PostUploadResponses = {
    /**
     * the UUID of the created job batch for the upload
     */
    202: string;
};

export type PostUploadResponse = PostUploadResponses[keyof PostUploadResponses];

export type GetUsersAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/all';
};

export type GetUsersAllErrors = {
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetUsersAllError = GetUsersAllErrors[keyof GetUsersAllErrors];

export type GetUsersAllResponses = {
    /**
     * OK
     */
    200: Array<DatabasePublicUser>;
};

export type GetUsersAllResponse = GetUsersAllResponses[keyof GetUsersAllResponses];

export type PostUsersCreateData = {
    /**
     * User Login Details
     */
    body: ApiLoginCredentials;
    path?: never;
    query?: never;
    url: '/users/create';
};

export type PostUsersCreateErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostUsersCreateError = PostUsersCreateErrors[keyof PostUsersCreateErrors];

export type PostUsersCreateResponses = {
    /**
     * OK
     */
    200: DatabasePublicUser;
};

export type PostUsersCreateResponse = PostUsersCreateResponses[keyof PostUsersCreateResponses];

export type DeleteUsersPermissionsByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query: {
        /**
         * Permissions to revoke in the form read/write/delete:name
         */
        permission: Array<string>;
    };
    url: '/users/permissions/{id}';
};

export type DeleteUsersPermissionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteUsersPermissionsByIdError = DeleteUsersPermissionsByIdErrors[keyof DeleteUsersPermissionsByIdErrors];

export type DeleteUsersPermissionsByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteUsersPermissionsByIdResponse = DeleteUsersPermissionsByIdResponses[keyof DeleteUsersPermissionsByIdResponses];

export type GetUsersPermissionsByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/permissions/{id}';
};

export type GetUsersPermissionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetUsersPermissionsByIdError = GetUsersPermissionsByIdErrors[keyof GetUsersPermissionsByIdErrors];

export type GetUsersPermissionsByIdResponses = {
    /**
     * OK
     */
    200: Array<DataPermission>;
};

export type GetUsersPermissionsByIdResponse = GetUsersPermissionsByIdResponses[keyof GetUsersPermissionsByIdResponses];

export type PostUsersPermissionsByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query: {
        /**
         * Permissions to grant
         */
        permission: Array<string>;
    };
    url: '/users/permissions/{id}';
};

export type PostUsersPermissionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostUsersPermissionsByIdError = PostUsersPermissionsByIdErrors[keyof PostUsersPermissionsByIdErrors];

export type PostUsersPermissionsByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostUsersPermissionsByIdResponse = PostUsersPermissionsByIdResponses[keyof PostUsersPermissionsByIdResponses];

export type DeleteUsersProfilePictureByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/profile-picture/{id}';
};

export type DeleteUsersProfilePictureByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteUsersProfilePictureByIdError = DeleteUsersProfilePictureByIdErrors[keyof DeleteUsersProfilePictureByIdErrors];

export type DeleteUsersProfilePictureByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteUsersProfilePictureByIdResponse = DeleteUsersProfilePictureByIdResponses[keyof DeleteUsersProfilePictureByIdResponses];

export type GetUsersProfilePictureByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/profile-picture/{id}';
};

export type GetUsersProfilePictureByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetUsersProfilePictureByIdError = GetUsersProfilePictureByIdErrors[keyof GetUsersProfilePictureByIdErrors];

export type GetUsersProfilePictureByIdResponses = {
    /**
     * profile picture file data
     */
    200: unknown;
};

export type PostUsersProfilePictureByIdData = {
    body: {
        /**
         * New profile picture
         */
        picture: Blob | File;
    };
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/profile-picture/{id}';
};

export type PostUsersProfilePictureByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostUsersProfilePictureByIdError = PostUsersProfilePictureByIdErrors[keyof PostUsersProfilePictureByIdErrors];

export type PostUsersProfilePictureByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostUsersProfilePictureByIdResponse = PostUsersProfilePictureByIdResponses[keyof PostUsersProfilePictureByIdResponses];

export type PostUsersVisibilityByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query: {
        /**
         * Visibility mode (0, 1, or 2)
         */
        mode: number;
    };
    url: '/users/visibility/{id}';
};

export type PostUsersVisibilityByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type PostUsersVisibilityByIdError = PostUsersVisibilityByIdErrors[keyof PostUsersVisibilityByIdErrors];

export type PostUsersVisibilityByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type PostUsersVisibilityByIdResponse = PostUsersVisibilityByIdResponses[keyof PostUsersVisibilityByIdResponses];

export type DeleteUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type DeleteUsersByIdError = DeleteUsersByIdErrors[keyof DeleteUsersByIdErrors];

export type DeleteUsersByIdResponses = {
    /**
     * OK
     */
    200: ApiMessageResponse;
};

export type DeleteUsersByIdResponse = DeleteUsersByIdResponses[keyof DeleteUsersByIdResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Bad Request
     */
    400: ApiBadRequestResponse;
    /**
     * Internal Server Error
     */
    500: ApiServerErrorResponse;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * OK
     */
    200: DatabasePublicUser;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];
